AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AlertaUTEC - Backend de Incidentes

Globals:
  Function:
    Runtime: python3.12
    Timeout: 15
    MemorySize: 256

Parameters:
  LabRoleArn:
    Type: String
    Default: 'arn:aws:iam::527785891672:role/LabRole'
    Description: ARN del LabRole para AWS Academy
  IncidentsTableName:
    Type: String
    Default: 'AlertaUTEC-Incidents'
    Description: Nombre de la tabla DynamoDB de incidentes

Resources:
  # ==================== DYNAMODB TABLE ====================
  IncidentsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref IncidentsTableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: incidentId
          AttributeType: S
      KeySchema:
        - AttributeName: incidentId
          KeyType: HASH
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES

  # ==================== API GATEWAY ====================
  IncidentsApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: AlertaUTEC-Incidents-API
      StageName: prod
      Cors:
        AllowMethods: "'GET,POST,PATCH,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowOrigin: "'*'"

  CreateIncidentFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: handlers.create_incident
      Role: !Ref LabRoleArn
      Environment:
        Variables:
          INCIDENTS_TABLE: !Ref IncidentsTableName
      Events:
        CreateIncident:
          Type: Api
          Properties:
            Path: /incidents
            Method: post
            RestApiId: !Ref IncidentsApi

  UpdateIncidentFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: handlers.update_incident
      Role: !Ref LabRoleArn
      Environment:
        Variables:
          INCIDENTS_TABLE: !Ref IncidentsTableName
      Events:
        UpdateIncident:
          Type: Api
          Properties:
            Path: /incidents/{id}
            Method: patch
            RestApiId: !Ref IncidentsApi

  ListIncidentsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: handlers.list_incidents
      Role: !Ref LabRoleArn
      Environment:
        Variables:
          INCIDENTS_TABLE: !Ref IncidentsTableName
      Events:
        ListIncidents:
          Type: Api
          Properties:
            Path: /incidents
            Method: get
            RestApiId: !Ref IncidentsApi

  # ==================== COMMENTS FUNCTIONS ====================
  CreateCommentFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: comments.create_comment
      Role: !Ref LabRoleArn
      Environment:
        Variables:
          INCIDENTS_TABLE: !Ref IncidentsTableName
      Events:
        CreateComment:
          Type: Api
          Properties:
            Path: /incidents/{incidentId}/comments
            Method: post
            RestApiId: !Ref IncidentsApi

  ListCommentsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: comments.list_comments
      Role: !Ref LabRoleArn
      Environment:
        Variables:
          INCIDENTS_TABLE: !Ref IncidentsTableName
      Events:
        ListComments:
          Type: Api
          Properties:
            Path: /incidents/{incidentId}/comments
            Method: get
            RestApiId: !Ref IncidentsApi

  DeleteCommentFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: comments.delete_comment
      Role: !Ref LabRoleArn
      Environment:
        Variables:
          INCIDENTS_TABLE: !Ref IncidentsTableName
      Events:
        DeleteComment:
          Type: Api
          Properties:
            Path: /incidents/{incidentId}/comments/{commentId}
            Method: delete
            RestApiId: !Ref IncidentsApi

Outputs:
  ApiUrl:
    Description: URL base de la API REST de incidentes
    Value: !Sub "https://${IncidentsApi}.execute-api.${AWS::Region}.amazonaws.com/prod"
  
  IncidentsTableStreamArn:
    Description: ARN del DynamoDB Stream de la tabla Incidents
    Value: !GetAtt IncidentsTable.StreamArn
    Export:
      Name: AlertaUTEC-IncidentsStreamArn
